In [1321]:
import pandas as pd
import numpy as np

In [1322]:
df=pd.read_csv('credit_card_fraud_synthetic.csv')

In [1323]:
df

       Time        V1        V2        V3        V4        V5   Amount  Class
0    121958 -2.289061 -1.313758 -0.452562 -0.392802  0.224787  1600.89      0
1    146867  1.432482 -1.095302 -0.129910 -1.362911 -1.017335  4191.85      0
2    131932  1.214722 -0.168797  0.581433  0.699020  0.964415  3271.32      0
3    103694 -0.880864  0.110956 -0.203236 -0.243510  0.362543  1377.51      0
4    119879 -0.881879  0.786970  1.110118  0.015365 -1.135162  4838.72      0
..      ...       ...       ...       ...       ...       ...      ...    ...
995  150168 -0.239297 -0.093612  0.674449 -1.934307  0.201932  1863.34      0
996   67728 -0.717823  0.704535  0.347665  0.158832 -0.295808  1152.10      0
997  165088 -0.484361  1.489765 -0.921505 -0.624253  1.588061  2805.25      0
998   11246  1.053057 -0.885100 -0.391480  0.000222 -0.077757   672.88      0
999  149453  2.033305  1.457079 -0.159335  1.651450 -0.186564  1601.27      0

[1000 rows x 8 columns]

In [1324]:
df.head()

     Time        V1        V2        V3        V4        V5   Amount  Class
0  121958 -2.289061 -1.313758 -0.452562 -0.392802  0.224787  1600.89      0
1  146867  1.432482 -1.095302 -0.129910 -1.362911 -1.017335  4191.85      0
2  131932  1.214722 -0.168797  0.581433  0.699020  0.964415  3271.32      0
3  103694 -0.880864  0.110956 -0.203236 -0.243510  0.362543  1377.51      0
4  119879 -0.881879  0.786970  1.110118  0.015365 -1.135162  4838.72      0

In [1325]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    1000 non-null   int64
 1   V1      1000 non-null   float64
 2   V2      1000 non-null   float64
 3   V3      1000 non-null   float64
 4   V4      1000 non-null   float64
 5   V5      1000 non-null   float64
 6   Amount  1000 non-null   float64
 7   Class   1000 non-null   int64
dtypes: float64(6), int64(2)
memory usage: 62.6 KB

In [1326]:
X=df.drop('Class',axis=1)
y=df['Class']

In [1327]:
from sklearn.model_selection import train_test_split

In [1328]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [1329]:
from sklearn.linear_model import LogisticRegression

In [1330]:
model=LogisticRegression()

In [1331]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [1332]:
model.fit(X_train,y_train)

LogisticRegression()

In [1333]:
y_pred=model.predict(X_test)

In [1334]:
from sklearn.metrics import accuracy_score

In [1335]:
accuracy_score(y_test,y_pred)

0.995

In [1336]:
#i can see overfitting here due the fraud's being less so i should use stratify for a better training
df["Class"].value_counts()

Class
0    982
1     18
Name: count, dtype: int64

In [1343]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42,stratify=y)

In [1345]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [1346]:
model.fit(X_train,y_train)

LogisticRegression()

In [1339]:
model.predict(X_test)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0])

In [1340]:
y_pred=model.predict(X_test)

In [1341]:
accuracy_score(y_test,y_pred)

0.97

**Hence i can see a more realistic prediction than the previous predictions**